test4

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build Project
+name: Build and Test
 
 on:
   push:
@@ -41,3 +41,22 @@ jobs:
 
       - name: Build project
         run: cmake --build build
+      
+      - name: Test project
+	run: ｜
+	  if [ "$(uname)" == "Darwin" ]; then
+            DYLD_LIBRARY_PATH=../src ./test_mymath || exit 1	
+ 	  else
+	    ./test_mymath || exit 1
+	  fi
+
+      - name: Test Results
+	run: |
+	  if [ $? eq 0]
+	  then 
+	    echo "Test passed"
+	  else
+	    echo "Test failed"
+	    exit 1
+	  fi
+
